"""add language to posts

Revision ID: 764a8aa9afa9
Revises: 970bf02622d0
Create Date: 2019-07-31 10:21:47.023969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764a8aa9afa9'
down_revision = '970bf02622d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
