"""followers

Revision ID: 970bf02622d0
Revises: 99b30ce69473
Create Date: 2019-07-29 18:20:48.956467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970bf02622d0'
down_revision = '99b30ce69473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
